# Generated by Django 4.2.7 on 2023-11-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0002_rename_longtitude_station_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="description",
            field=models.TextField(default="Straight to the point of destination"),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("source", "destination", "distance"), name="unique_route"
            ),
        ),
    ]
