# Generated by Django 4.2.7 on 2023-11-10 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0004_alter_crew_options_station_image_train_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.FloatField(
                validators=[django.core.validators.MaxValueValidator(360)]
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.FloatField(
                validators=[django.core.validators.MaxValueValidator(360)]
            ),
        ),
    ]
