# Generated by Django 4.2.7 on 2023-11-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0007_crew_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crew",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True
            ),
        ),
    ]
